"""L1 verification — Trace + formulae -> SMV text emitter for NuSMV.

Encodes a finite Trace as a deterministic transition system in SMV format.
Like ispl.py, this is bounded model checking: a single `position` variable
advances through each move, and DEFINE clauses expose atomic propositions.

Subprocess invocation of NuSMV lives in tests/integration/ only.
"""

from __future__ import annotations

from collections.abc import Iterable

from council.dialect.trace import Trace
from council.symbolic.verify.ispl import ltlf_to_ctl
from council.symbolic.verify.ltlf import LTLf


def _ctl_to_smv(ctl: str) -> str:
    """Map MCMAS CTL syntax to NuSMV CTL syntax (mostly drop-in identical).

    Differences:
      - NuSMV uses `&` / `|` instead of `and` / `or`
      - NuSMV uses `!` for negation (same as MCMAS)
      - NuSMV uses `->` for implication (same)
      - NuSMV CTL: `EF`, `AG`, `EX`, `E[a U b]`, `A[a U b]` (same)
    """
    return ctl.replace(" and ", " & ").replace(" or ", " | ")


def trace_to_smv(trace: Trace, formulae: Iterable[LTLf]) -> str:
    """Encode `(trace, formulae)` as an SMV module for NuSMV.

    Output structure:
      MODULE main
        VAR
          position : 0..N;
        DEFINE
          <ap_name> := position in {i, j, k};   -- per AP
        ASSIGN
          init(position) := 0;
          next(position) := position < N ? position + 1 : N;
        SPEC
          <CTL formula>;
    """
    events = trace.to_events()
    n = len(events)

    lines = [
        f"-- Generated by council.symbolic.verify.smv ({n} events)",
        "MODULE main",
    ]

    # VAR
    lines.append("  VAR")
    if n == 0:
        lines.append("    position : 0..0;")
    else:
        lines.append(f"    position : 0..{n};")

    # DEFINE — one boolean AP per to_events() key
    if events:
        ap_keys = sorted({k for e in events for k, v in e.items() if isinstance(v, bool)})
        if ap_keys:
            lines.append("  DEFINE")
            for ap in ap_keys:
                true_positions = [i for i, e in enumerate(events) if bool(e.get(ap, False))]
                if true_positions:
                    set_str = ", ".join(str(i) for i in true_positions)
                    lines.append(f"    {ap} := position in {{ {set_str} }};")
                else:
                    lines.append(f"    {ap} := FALSE;")

    # ASSIGN
    lines.append("  ASSIGN")
    lines.append("    init(position) := 0;")
    if n == 0:
        lines.append("    next(position) := 0;")
    else:
        lines.append(f"    next(position) := case position < {n} : position + 1; TRUE : {n}; esac;")

    # SPEC
    for f in formulae:
        ctl = ltlf_to_ctl(f)
        lines.append(f"  SPEC {_ctl_to_smv(ctl)};")

    return "\n".join(lines) + "\n"
